export const AUTH_BACKEND_ERROR_KEY = {
  // LOGIN (EMAIL/PHONE)
  UserWithEmailExists: 'VALIDATION_BACK.USER_WITH_THIS_EMAIL_ALREADY_EXIST',
  UserWithPhoneExists: 'VALIDATION_BACK.USER_WITH_THIS_PHONE_ALREADY_EXIST',
  UserWithSocialExists: 'VALIDATION_BACK.USER_WITH_THIS_SOCIAL_IDENTITY_ALREADY_EXIST',
  WrongLoginOrPassword: 'VALIDATION_BACK.WRONG_LOGIN_OR_PASSWORD',
  EmailBadDomain: 'VALIDATION_BACK.EMAIL_BAD_DOMAIN',
  EmailInvalidFormat: 'VALIDATION_BACK.EMAIL_INVALID_FORMAT_ERROR',
  EmailInvalidLength: 'VALIDATION_BACK.EMAIL_INVALID_LENGTH_FORMAT_ERROR',
  EmailVerificationNotCompleted: 'VALIDATION_BACK.EMAIL_VERIFICATION_NOT_COMPLETED',
  PhoneNotValid: 'VALIDATION_BACK.PHONE_NOT_VALID',
  PhoneVerificationNotCompleted: 'VALIDATION_BACK.PHONE_VERIFICATION_NOT_COMPLETED',
  WrongPhoneConfirmCode: 'VALIDATION_BACK.WRONG_PHONE_CONFIRM_CODE',
  RegFromEmailForbidden: 'VALIDATION_BACK.ANTI_FRAUD.REGISTRATION_FROM_EMAIL_FORBIDDEN',
  ValueShouldNotBeBlank: 'VALIDATION_BACK.VALUE_SHOULD_NOT_BE_BLANK',

  // PASSWORD
  PasswordBadChars: 'VALIDATION_BACK.PASSWORD_BAD_CHARS',
  PasswordUnsupportedChars: 'VALIDATION_BACK.PASSWORD_CONTAINS_UNSUPPORTED_CHARS',
  PasswordInvalidLength: 'VALIDATION_BACK.PASSWORD_INVALID_LENGTH_FORMAT_ERROR',
  PasswordIsWeak: 'VALIDATION_BACK.PASSWORD_IS_WEAK',
  PasswordRepeating: 'VALIDATION_BACK.PASSWORD_REPEATING_VALIDATION',
  PasswordSameAsEmail: 'VALIDATION_BACK.PASSWORD_SHOULD_NOT_COINCIDE_WITH_THE_EMAIL',
  PasswordSameAsPhone: 'VALIDATION_BACK.PASSWORD_SHOULD_NOT_COINCIDE_WITH_THE_PHONE',
  PasswordModified: 'VALIDATION_BACK.PASSWORD_MODIFIED',

  // RESTORE PASSWORD
  RestorePasswordCodeNotFound: 'VALIDATION_BACK.RESTORE_PASSWORD_CODE_NOT_FOUND',
  RestorePasswordCodeSent: 'VALIDATION_BACK.RESTORE_PASSWORD_CODE_SENT',
  RestorePasswordUserNotFound: 'VALIDATION_BACK.RESTORE_PASSWORD_CODE_USER_NOT_FOUND',
  RestorePasswordError: 'VALIDATION_BACK.RESTORE_PASSWORD_ERROR_TRY_LATER',
  WrongRestoreCode: 'VALIDATION_BACK.WRONG_RESTORE_CODE',

  // COUNTRY
  RegFromCountryForbidden: 'VALIDATION_BACK.ANTI_FRAUD.REGISTRATION_FROM_COUNTRY_FORBIDDEN',
  LoginFromCountryForbidden: 'VALIDATION_BACK.ANTI_FRAUD.LOGIN_FROM_COUNTRY_FORBIDDEN',
  NotAllowedDomainCountry: 'VALIDATION_BACK.NOT_ALLOWED_DOMAIN_COUNTRY',
  RegNotAllowedDomainCountry: 'VALIDATION_BACK.REGISTRATION_NOT_ALLOWED_DOMAIN_COUNTRY',

  // CURRENCY
  CurrencyNotSupported: 'VALIDATION_BACK.CURRENCY_NOT_SUPPORTED',

  // PROMO CODE
  PromoNotFound: 'VALIDATION_BACK.PROMO_CODE_NOT_FOUND',
  PromoAttemptsExceed: 'VALIDATION_BACK.PROMO_CODE_ATTEMPTS_EXCEED',
  PromoDuplicate: 'VALIDATION_BACK.PROMO_CODE_DUPLICATE_ACTIVATION',
  PromoExpired: 'VALIDATION_BACK.PROMO_CODE_CAMPAIGN_EXPIRED',
  PromoNotActive: 'VALIDATION_BACK.PROMO_CODE_CAMPAIGN_NOT_ACTIVE',
  PromoUnknownError: 'VALIDATION_BACK.PROMO_CODE_UNKNOWN_ERROR',
  PromoLimitReached: 'VALIDATION_BACK.PROMO_CODE_ACTIVATION_LIMIT_REACHED',
  PromoLimitReachedUnexpectedly: 'VALIDATION_BACK.PROMO_CODE_ACTIVATION_LIMIT_REACHED_UNEXPECTEDLY',
  PartnerCodesDoNotMatch: 'VALIDATION_BACK.PARTNER_CODES_DO_NOT_MATCH',

  // ACCEPT TERMS
  RulesNotAccepted: 'VALIDATION_BACK.RULES_NOT_ACCEPTED',

  // ACCOUNT STATUS & ANTI-FRAUD
  AccountBlocked: 'VALIDATION_BACK.ANTI_FRAUD.ACCOUNT_IS_BLOCKED',
  AccountIsFraud: 'VALIDATION_BACK.ACCOUNT_IS_FRAUD',
  AccountRestricted: 'VALIDATION_BACK.ACCOUNT_RESTRICTED',
  UserBlocked: 'VALIDATION_BACK.USER_BLOCKED',
  SelfExclusion: 'VALIDATION_BACK.SELF_EXCLUSION_ACTIVATED',
  AlreadyHaveAccount: 'VALIDATION_BACK.ANTI_FRAUD.ALREADY_HAVE_ACCOUNT',
  DeclinedAlreadyHaveAccount: 'VALIDATION_BACK.ANTI_FRAUD.DECLINED_ALREADY_HAVE_ACCOUNT',
  RegRejected: 'VALIDATION_BACK.ANTI_FRAUD.REGISTRATION_REJECTED',
  LoginRejected: 'VALIDATION_BACK.ANTI_FRAUD.LOGIN_REJECTED',

  // RATE LIMITING
  TooManyAttempts: 'VALIDATION_BACK.TOO_MANY_ATTEMPTS',
  TooManyAttemptsSlowDown: 'VALIDATION_BACK.TOO_MANY_ATTEMPTS_SLOW_DOWN',
} as const

export type BackendErrorKey = typeof AUTH_BACKEND_ERROR_KEY[keyof typeof AUTH_BACKEND_ERROR_KEY];