export const AUTH_BACKEND_ERROR_KEY = {
  // LOGIN (EMAIL/PHONE)
  USER_WITH_EMAIL_EXISTS: 'USER_WITH_THIS_EMAIL_ALREADY_EXIST',
  USER_WITH_PHONE_EXISTS: 'USER_WITH_THIS_PHONE_ALREADY_EXIST',
  USER_WITH_SOCIAL_EXISTS: 'USER_WITH_THIS_SOCIAL_IDENTITY_ALREADY_EXIST',
  WRONG_LOGIN_OR_PASSWORD: 'WRONG_LOGIN_OR_PASSWORD',
  EMAIL_BAD_DOMAIN: 'EMAIL_BAD_DOMAIN',
  EMAIL_INVALID_FORMAT: 'EMAIL_INVALID_FORMAT_ERROR',
  EMAIL_INVALID_LENGTH: 'EMAIL_INVALID_LENGTH_FORMAT_ERROR',
  EMAIL_VERIFICATION_NOT_COMPLETED: 'EMAIL_VERIFICATION_NOT_COMPLETED',
  REG_FROM_EMAIL_FORBIDDEN: 'ANTI_FRAUD.REGISTRATION_FROM_EMAIL_FORBIDDEN',
  VALUE_SHOULD_NOT_BE_BLANK: 'VALUE_SHOULD_NOT_BE_BLANK',

  // PASSWORD
  PASSWORD_BAD_CHARS: 'PASSWORD_BAD_CHARS',
  PASSWORD_UNSUPPORTED_CHARS: 'PASSWORD_CONTAINS_UNSUPPORTED_CHARS',
  PASSWORD_INVALID_LENGTH: 'PASSWORD_INVALID_LENGTH_FORMAT_ERROR',
  PASSWORD_IS_WEAK: 'PASSWORD_IS_WEAK',
  PASSWORD_REPEATING: 'PASSWORD_REPEATING_VALIDATION',
  PASSWORD_SAME_AS_EMAIL: 'PASSWORD_SHOULD_NOT_COINCIDE_WITH_THE_EMAIL',
  PASSWORD_SAME_AS_PHONE: 'PASSWORD_SHOULD_NOT_COINCIDE_WITH_THE_PHONE',
  PASSWORD_MODIFIED: 'PASSWORD_MODIFIED',

  // RESTORE PASSWORD
  RESTORE_PASSWORD_CODE_NOT_FOUND: 'RESTORE_PASSWORD_CODE_NOT_FOUND',
  RESTORE_PASSWORD_CODE_SENT: 'RESTORE_PASSWORD_CODE_SENT',
  RESTORE_PASSWORD_USER_NOT_FOUND: 'RESTORE_PASSWORD_CODE_USER_NOT_FOUND',
  RESTORE_PASSWORD_ERROR: 'RESTORE_PASSWORD_ERROR_TRY_LATER',
  WRONG_RESTORE_CODE: 'WRONG_RESTORE_CODE',

  // COUNTRY
  REG_FROM_COUNTRY_FORBIDDEN: 'ANTI_FRAUD.REGISTRATION_FROM_COUNTRY_FORBIDDEN',
  LOGIN_FROM_COUNTRY_FORBIDDEN: 'ANTI_FRAUD.LOGIN_FROM_COUNTRY_FORBIDDEN',
  NOT_ALLOWED_DOMAIN_COUNTRY: 'NOT_ALLOWED_DOMAIN_COUNTRY',
  REG_NOT_ALLOWED_DOMAIN_COUNTRY: 'REGISTRATION_NOT_ALLOWED_DOMAIN_COUNTRY',

  // CURRENCY
  CURRENCY_NOT_SUPPORTED: 'CURRENCY_NOT_SUPPORTED',

  // PROMO CODE
  PROMO_NOT_FOUND: 'PROMO_CODE_NOT_FOUND',
  PROMO_ATTEMPTS_EXCEED: 'PROMO_CODE_ATTEMPTS_EXCEED',
  PROMO_DUPLICATE: 'PROMO_CODE_DUPLICATE_ACTIVATION',
  PROMO_EXPIRED: 'PROMO_CODE_CAMPAIGN_EXPIRED',
  PROMO_NOT_ACTIVE: 'PROMO_CODE_CAMPAIGN_NOT_ACTIVE',
  PROMO_UNKNOWN_ERROR: 'PROMO_CODE_UNKNOWN_ERROR',
  PROMO_LIMIT_REACHED: 'PROMO_CODE_ACTIVATION_LIMIT_REACHED',
  PROMO_LIMIT_REACHED_UNEXPECTEDLY: 'PROMO_CODE_ACTIVATION_LIMIT_REACHED_UNEXPECTEDLY',
  PARTNER_CODES_DO_NOT_MATCH: 'PARTNER_CODES_DO_NOT_MATCH',

  // ACCEPT TERMS
  RULES_NOT_ACCEPTED: 'RULES_NOT_ACCEPTED',

  // ACCOUNT STATUS & ANTI-FRAUD
  ACCOUNT_BLOCKED: 'ANTI_FRAUD.ACCOUNT_IS_BLOCKED',
  ACCOUNT_IS_FRAUD: 'ACCOUNT_IS_FRAUD',
  ACCOUNT_RESTRICTED: 'ACCOUNT_RESTRICTED',
  USER_BLOCKED: 'USER_BLOCKED',
  SELF_EXCLUSION: 'SELF_EXCLUSION_ACTIVATED',
  ALREADY_HAVE_ACCOUNT: 'ANTI_FRAUD.ALREADY_HAVE_ACCOUNT',
  DECLINED_ALREADY_HAVE_ACCOUNT: 'ANTI_FRAUD.DECLINED_ALREADY_HAVE_ACCOUNT',
  REG_REJECTED: 'ANTI_FRAUD.REGISTRATION_REJECTED',
  LOGIN_REJECTED: 'ANTI_FRAUD.LOGIN_REJECTED',

  // RATE LIMITING
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',
  TOO_MANY_ATTEMPTS_SLOW_DOWN: 'TOO_MANY_ATTEMPTS_SLOW_DOWN',
} as const;

export type AuthBackendErrorKey = typeof AUTH_BACKEND_ERROR_KEY[keyof typeof AUTH_BACKEND_ERROR_KEY];

export type UserDeviceInfo = {
  os?: string;
  screen_resolution?: string;
};

export type LoginDTO = Record<string, unknown> &
  UserDeviceInfo & {
    _password: string;
    _username: string;
    captcha_key?: string;
  };

export type RegisterDTO = UserDeviceInfo & {
  accept_notifications?: boolean;
  accept_terms: boolean;
  auth_type: string;
  chosen_country: string;
  currency: string;
  localization: string;
  login: string;
  password: string;
  promo_code: string;
  captcha_key?: string;
}

export interface IChangePasswordDTO {
  code?: string;
  password: string;
}

export enum LoginResourceStep {
  EMAIL_VERIFICATION = 'email_verification',
}

export type LoginErrorResource = {
  message: AuthBackendErrorKey;
};

export type LoginErrorCaptchaRequiredResource = {
  captcha_required: boolean;
};

export type LoginSuccessResource = {
  step?: LoginResourceStep | string;
};

export type LoginResource = LoginSuccessResource | LoginErrorResource | LoginErrorCaptchaRequiredResource;

export interface ILogoutResource {
  redirect: string;
  success: boolean;
}

export enum RegisterBackendValidationFieldKeys {
  LOGIN = "login",
  LOGIN_FORBIDDEN = "loginForbidden",
  PASSWORD = "password",
  COUNTRY = "chosen_country",
  CURRENCY = "currency",
  PROMO_CODE = "promo_code",
  ACCEPT_TERMS = "accept_terms",
}

type RegisterErrors = Partial<Record<RegisterBackendValidationFieldKeys, AuthBackendErrorKey[]>>;

type RegisterSuccessResource = {
  success: true;
  user_is_logged: boolean;
  isAlreadyRegistered?: boolean;
};

type RegisterErrorResource = Partial<{
  success: false;
  message: AuthBackendErrorKey;
  error: {
    data?: {
      message?: AuthBackendErrorKey;
    }
  }
  errors: RegisterErrors;
}>;

export type RegisterResource = RegisterSuccessResource | RegisterErrorResource;

export const IBIZA_ERROR_KEYS = {
  // INVALID
  BLACKLISTED: 'IBIZA.INVALID.BLACKLISTED',
  INVALID_DOMAIN: 'IBIZA.INVALID.INVALID_DOMAIN',
  INVALID_EMAIL: 'IBIZA.INVALID.INVALID_EMAIL',
  INVALID_REJECTED_EMAIL: 'IBIZA.INVALID.REJECTED_EMAIL',

  // RISKY
  RISKY_INBOX_FULL: 'IBIZA.RISKY.INBOX_FULL',
  RISKY_NON_PERSONAL: 'IBIZA.RISKY.NON_PERSONAL',
  RISKY_RISKY: 'IBIZA.RISKY.RISKY',
  RISKY_TEMPORARY: 'IBIZA.RISKY.TEMPORARY',
  RISKY_TIMEOUT: 'IBIZA.RISKY.TIMEOUT',

  // UNKNOWN
  UNKNOWN_UNKNOWN: 'IBIZA.UNKNOWN.UNKNOWN',

  // VALID
  VALID_ACCEPTED_EMAIL: 'IBIZA.VALID.ACCEPTED_EMAIL',
  VALID_WHITELISTED: 'IBIZA.VALID.WHITELISTED',
} as const;

export type IbizaErrorKey = typeof IBIZA_ERROR_KEYS[keyof typeof IBIZA_ERROR_KEYS];

export interface IVerifyEmailResource {
  result: IbizaErrorKey;
}
